config/routes.rb
Riddler::Application.routes.draw do
  root :to => "questions#index"
  resources :questions do
    resources :answers
  end

end

app/models/answer.rb
class Answer
  include MongoMapper::Document

  key :answer, String

  belongs_to :question

  validates_presence_of :answer

end

app/models/question.rb
class Question
  include MongoMapper::Document

  key :ask, String
  key :detail, String

  many :answers
    
  validates_presence_of :ask
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :find_question
  before_filter :find_answer, :only => [:show, :update, :edit, :destroy]

  def index
  end

  def new
    @answer = @question.answers.build
  end

  def create
    @answer = @question.answers.build(params[:answer])
    if @answer.save
      flash[:notice]="Answer has been created."
      redirect_to [@question, @answer]
    else
      flash[:alert]="Answer has not been created."
      render :action => "new"
    end
  end

  private
  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = @question.answers.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :find_question, :only => [:show, :update, :edit, :destroy]
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params[:question])
    if @question.save
      flash[:notice] = "Your question has been created."
      redirect_to @question
    else
      flash[:alert] = "Unable to create question."
      render :new
    end
  end

  def show
    #
  end

  def edit
  end

  def update
    if @question.update_attributes(params[:question])
      flash[:notice]="Question has been updated."
      redirect_to @question
    else
      flash[:alert]="Question has not been updated."
      render :action => "edit" 
    end
  end

  def destroy
    @question.destroy
    flash[:notice]= "Question has been deleted."
    redirect_to questions_path
  end

private
  def find_question
    @question = Question.find(params[:id])
  rescue MongoMapper::DocumentNotFound
    flash[:alert] = "The question you were looking for could not be found."
    redirect_to questions_path
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>
  <div class="panel large-10">
    <%= f.error_messages %>
    <%= f.label :answer %>
    <%= f.text_field :answer %>
    <%= f.submit :class => "button" %>
  </div>
<% end %>

app/views/answers/new.html.erb
<div class="panel large-10">
  <h2>New Answer</h2>
  <%= render "form" %>
</div>

app/views/answers/show.html.erb
<div id="ticket" class="panel large-10">
  <h2>Answer for<%= @question.ask %></h2>
  <%= simple_format(@answer.answer) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
    <% if(:title) %>
      <%= yield(:title) %>
    <% else %>
      Riddler-Question and Answer
    <% end %>
  </head>

  <body>
    <div class="row">
      
      <% flash.each do |key, value| %>
          <div id = "<%= key %>" class="flash panel large-10">
            <%= value %>
          </div>
      <% end %>
      <%= yield %>
    </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <div class="panel large-10">
    <%= f.error_messages %>
    <h4><%= f.label :ask %></h4>
    <%= f.text_field :ask %>
    <h4><%= f.label :detail %></h4>
    <%= f.text_field :detail %>
    <%= f.submit :class => "button" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class="panel large-10">
  <h2>Editing Question <%= @question.ask %></h2>
  <%= render "form" %>
</div>

app/views/questions/index.html.erb
<div class="panel large-10 large-centered">
  <h2>Questions Questions Questions!</h2>
  <ul>
    <% @questions.each do |question| %>
      <li><%= link_to question.ask, question %></li>
    <% end %>
  </ul>

  <%= link_to "Ask a New Question", new_question_path, :class => "button" %>
</div>

app/views/questions/new.html.erb
<h2>Ask a New Question</h2>
<%= render "form" %>

app/views/questions/show.html.erb
<div class="panel large-10">
  <h4><%= @question.ask %></h4>
  <h6>Here's some details you may or may not need:</h6>
  <p><%= @question.detail %></p>
  <%= link_to "Edit Question", edit_question_path, :class => "button" %>
  <%= link_to "Delete Question", question_path(@question), 
                                :method => :delete,
                                :confirm => "Are you sure you want to delete this question?",
                                :class => "button" %>
  <%= link_to "Answer Question", new_question_answer_path(@question) %>                    
</div>
<div id="tickets" class="panel large-10">
  <ul>
    <% @question.answers.each do |answer| %>
    <li>
        <%= link_to answer.answer,[@question, @answer] %>
    </li>
    <% end %>
  </ul>
</div>